name: Release
on:
  workflow_dispatch:
    inputs:
      job:
        required: true
        type: choice
        options: ['prod', 'test', 'all']
  push:
    branches: ['dev', 'main']

jobs:
  prod:
    if: contains(github.event.head_commit.message, '[prod]') || contains(github.event.head_commit.message, '[all]') || github.event.inputs.job == 'prod' || github.event.inputs.job == 'all'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install dependencies & build
        env:
          VITE_BASE_URL: 'u3com-app'
          VITE_ENV: 'prod'
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        #   cname: app.u3.com
  test:
    if: contains(github.event.head_commit.message, '[test]') || contains(github.event.head_commit.message, '[all]') || github.event.inputs.job == 'test' || github.event.inputs.job == 'all'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Install dependencies & build
        env:
          VITE_BASE_URL: 'u3com-app'
          VITE_ENV: 'test'
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        #   cname: app.u3.com
